const members = {
  "01": {
    name: "VIVEK VIJAYAN",
    role: "WEBMASTER",
    department: "Executive",
    bio: "IEEE MACE SB ExeCom'26",
    avatar: "Alone.jpg",
    linkedin: "https://www.linkedin.com/in/vivek-vijayan-6a7aa6281",
    github: "https://github.com",
    whatsapp: "https://wa.me/917592840401",
    email: "mailto:vivekkedharam@gmail.com"
  },
  "02": {
    name: "Member 02",
    role: "Chairperson",
    department: "Executive",
    bio: "Student Branch Chair overseeing operations, planning, and leadership.",
    avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=2",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    whatsapp: "https://wa.me/919999999999",
    email: "mailto:member02@example.com"
  },
  "03": {
    name: "Member 03",
    role: "Vice Chair",
    department: "Executive",
    bio: "Assisting branch leadership, overseeing committee initiatives and programs.",
    avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=3",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    whatsapp: "https://wa.me/919999999999",
    email: "mailto:member03@example.com"
  },
  "04": {
    name: "Member 04",
    role: "Secretary",
    department: "Executive",
    bio: "Documentation, reporting, meeting minutes, and official correspondence.",
    avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=4",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    whatsapp: "https://wa.me/919999999999",
    email: "mailto:member04@example.com"
  },
  "05": {
    name: "Member 05",
    role: "Treasurer",
    department: "Finance",
    bio: "Managing branch accounts, budgeting, sponsorships, and event finances.",
    avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=5",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    whatsapp: "https://wa.me/919999999999",
    email: "mailto:member05@example.com"
  },
  "06": {
    name: "Member 06",
    role: "Joint Secretary",
    department: "Executive",
    bio: "Assisting operations, internal communications, and branch reporting.",
    avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=6",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    whatsapp: "https://wa.me/919999999999",
    email: "mailto:member06@example.com"
  },
  "07": {
    name: "Member 07",
    role: "Technical Coordinator",
    department: "Technical",
    bio: "Overseeing technical initiatives, hackathons, and lab projects.",
    avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=7",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    whatsapp: "https://wa.me/919999999999",
    email: "mailto:member07@example.com"
  },
  "08": {
    name: "Member 08",
    role: "Design Lead",
    department: "Creative & Media",
    bio: "Leading creative visual identity, posters, and design systems.",
    avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=8",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    whatsapp: "https://wa.me/919999999999",
    email: "mailto:member08@example.com"
  },
  "09": {
    name: "Member 09",
    role: "Publicity Lead",
    department: "Public Relations",
    bio: "Handling branch publicity, campaign outreach, and social engagement.",
    avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=9",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    whatsapp: "https://wa.me/919999999999",
    email: "mailto:member09@example.com"
  },
  "10": {
    name: "Member 10",
    role: "Membership Development Chair",
    department: "Membership",
    bio: "Driving member retention, growth, and IEEE benefit onboarding.",
    avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=10",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    whatsapp: "https://wa.me/919999999999",
    email: "mailto:member10@example.com"
  },
  "11": {
    name: "Member 11",
    role: "WIE Chair",
    department: "Women in Engineering",
    bio: "Empowering women in STEM through workshops and mentorship programs.",
    avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=11",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    whatsapp: "https://wa.me/919999999999",
    email: "mailto:member11@example.com"
  },
  "12": {
    name: "Member 12",
    role: "WIE Secretary",
    department: "Women in Engineering",
    bio: "Coordinating affinity group meetings, initiatives, and event records.",
    avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=12",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    whatsapp: "https://wa.me/919999999999",
    email: "mailto:member12@example.com"
  },
  "13": {
    name: "Member 13",
    role: "Computer Society Chair",
    department: "IEEE CS Chapter",
    bio: "Guiding software development, coding competitions, and tech talks.",
    avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=13",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    whatsapp: "https://wa.me/919999999999",
    email: "mailto:member13@example.com"
  },
  "14": {
    name: "Member 14",
    role: "Computer Society Secretary",
    department: "IEEE CS Chapter",
    bio: "Managing activities, membership engagement, and technical tracks.",
    avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=14",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    whatsapp: "https://wa.me/919999999999",
    email: "mailto:member14@example.com"
  },
  "15": {
    name: "Member 15",
    role: "PES Chair",
    department: "Power & Energy Society",
    bio: "Advancing green energy, sustainable technology, and power systems.",
    avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=15",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    whatsapp: "https://wa.me/919999999999",
    email: "mailto:member15@example.com"
  },
  "16": {
    name: "Member 16",
    role: "PES Secretary",
    department: "Power & Energy Society",
    bio: "Handling PES events, student engagement, and technical documentation.",
    avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=16",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    whatsapp: "https://wa.me/919999999999",
    email: "mailto:member16@example.com"
  },
  "17": {
    name: "Member 17",
    role: "RAS Chair",
    department: "Robotics & Automation",
    bio: "Organizing robotics build sessions, automation labs, and challenges.",
    avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=17",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    whatsapp: "https://wa.me/919999999999",
    email: "mailto:member17@example.com"
  },
  "18": {
    name: "Member 18",
    role: "RAS Secretary",
    department: "Robotics & Automation",
    bio: "Documenting robotics workshops, competitions, and project cohorts.",
    avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=18",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    whatsapp: "https://wa.me/919999999999",
    email: "mailto:member18@example.com"
  },
  "19": {
    name: "Member 19",
    role: "IAS Chair",
    department: "Industry Applications",
    bio: "Connecting students with industrial visits, safety, and applied engineering.",
    avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=19",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    whatsapp: "https://wa.me/919999999999",
    email: "mailto:member19@example.com"
  },
  "20": {
    name: "Member 20",
    role: "IAS Secretary",
    department: "Industry Applications",
    bio: "Coordinating industry interaction sessions and chapter reporting.",
    avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=20",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    whatsapp: "https://wa.me/919999999999",
    email: "mailto:member20@example.com"
  },
  "21": {
    name: "Member 21",
    role: "Content Lead",
    department: "Editorial & Content",
    bio: "Writing newsletters, announcements, and branch editorial coverage.",
    avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=21",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    whatsapp: "https://wa.me/919999999999",
    email: "mailto:member21@example.com"
  },
  "22": {
    name: "Member 22",
    role: "Social Media Manager",
    department: "Media & Branding",
    bio: "Managing digital channels, feeds, engagement reels, and campaigns.",
    avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=22",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    whatsapp: "https://wa.me/919999999999",
    email: "mailto:member22@example.com"
  },
  "23": {
    name: "Member 23",
    role: "Events Coordinator",
    department: "Operations",
    bio: "Logistics, venue planning, and scheduling for flagship conferences.",
    avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=23",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    whatsapp: "https://wa.me/919999999999",
    email: "mailto:member23@example.com"
  },
  "24": {
    name: "Member 24",
    role: "Sponsorship & PR Coordinator",
    department: "Corporate Relations",
    bio: "Securing brand sponsorships and external organizational partnerships.",
    avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=24",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    whatsapp: "https://wa.me/919999999999",
    email: "mailto:member24@example.com"
  },
  "25": {
    name: "Member 25",
    role: "Student Activities Coordinator",
    department: "Student Affairs",
    bio: "Student engagement, community meetups, and volunteer drives.",
    avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=25",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    whatsapp: "https://wa.me/919999999999",
    email: "mailto:member25@example.com"
  },
  "26": {
    name: "Member 26",
    role: "Executive Committee Member",
    department: "Executive",
    bio: "Supporting student branch operations, events, and sub-committee drives.",
    avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=26",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    whatsapp: "https://wa.me/919999999999",
    email: "mailto:member26@example.com"
  }
};
